export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
 UPDATE_CART_ITEM : "UPDATE_CART_ITEM",
 UPDATE_CART_ITEM_QUANTITY : "UPDATE_CART_ITEM_QUANTITY",
    CLEAR_CART : "CLEAR_CART",

  }